Test RSpec
Luzaks/Blocks-Enumerable-Methods pull request #3
Opened 2019-12-03 21:55 UTC by Luzaks

Pull request with all the tests for the Enumerable Methods.

2019-12-03 23:17 UTC, Forison requested changes
# Hi @Luzaks && @melisa👏, 
You have done a good job so far, 
* [ ] Let us refactor our code this way🙂
- ```let(:test_array) { [1, 2, 3, 4, 5] }```
we can call test_array in our expectation instead of having to redeclare new arrays.
- we have to state our expectations explicitly as pointed out below⬇️
## That is it guys, Kindly make these changes and submit code for review
Feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you. 
### Happy coding
Addo Boakye Forison

2019-12-03 23:17 UTC, Forison commented on spec/enumerable_spec.rb
> +RSpec.describe Enumerable do
```let(:test_array_one) { [10, 20, 20, 40, 50] }```
```let(:test_array_two) { [10, 20, 20, 40, 50] }``` this way we have a lean/dry code

2019-12-03 23:17 UTC, Forison commented on spec/enumerable_spec.rb
> +      expect([10, 20, 20, 40, 50].my_all? { |x| x > 6 }).to eql([10, 20, 20, 40, 50].all? { |x| x > 6 })
Note all of these methods are queries and the best way to test them is state explicitly what your expectation is.
```expect(test_array_one.my_all? { |x| x > 6 }).to eql(true)```.
Make sure you apply this any other place where this occurred

2019-12-03 23:17 UTC, Forison commented on spec/enumerable_spec.rb
> +      expect([nil, true, true].my_all?).to eql([nil, true, true].all?)
state explicitly what you are expecting instead of this ``` eql([nil, true, true].all?)```

2019-12-03 23:17 UTC, Forison commented on spec/enumerable_spec.rb
> +      expect(%w[ant bear cat].my_all?(/m/)).to eql(%w[ant bear cat].all?(/m/))
state explicitly what you are expecting instead of this  eql(%w[ant bear cat].all?(/m/))

2019-12-03 23:17 UTC, Forison commented on spec/enumerable_spec.rb
> +      expect([10, 20, 20, 40, 50].my_any? { |x| x > 6 }).to eql([10, 20, 20, 40, 50].any? { |x| x > 6 })
State explicitly what you are expecting

2019-12-03 23:17 UTC, Forison commented on spec/enumerable_spec.rb
> +      expect([13_123, nil, 431_321].my_any?(Integer)).to eql([13_123, nil, 431_321].any?(Integer))
state explicitly what you are expecting.
## Do the same in other instances🙂

2019-12-04 17:21 UTC, wathigo approved these changes
# Approved :smile: 
## Great test coverage :clap: 
### Let's move on :next_track_button: 

**Good luck :four_leaf_clover: 
Simon Wathigo**

2019-12-04 17:28 UTC, merged